Do not fail when GitHub release exists already

diff --git a/eng/templates/stages/release.yml b/eng/templates/stages/release.yml
--- a/eng/templates/stages/release.yml
+++ b/eng/templates/stages/release.yml
@@ -182,14 +182,25 @@ stages:
 
           echo -e "\n\nCreating GitHub release..."
 
-          gh release create "$(releaseTag)"         \
-            "$release_json#Release manifest"        \
-            --repo dotnet/dotnet                    \
-            --title "${{ parameters.releaseName }}" \
-            --target "$(dotnetDotnetCommit)"        \
-            --notes-file "$release_notes"           \
-            $prerelease                             \
-            $draft
+          set +e
+          result=$(gh release create "$(releaseTag)" \
+            "$release_json#Release manifest"         \
+            --repo dotnet/dotnet                     \
+            --title "${{ parameters.releaseName }}"  \
+            --target "$(dotnetDotnetCommit)"         \
+            --notes-file "$release_notes"            \
+            $prerelease                              \
+            $draft \
+            2>&1)
+
+          if [ $? -ne 0 ]; then
+            if [[ "$result" =~ "already exists" ]]; then
+              echo "##vso[task.logissue type=warning]GitHub release for $(dotnetDotnetCommit) already exists"
+            else
+              echo "##vso[task.logissue type=error]Failed to create the GitHub release: $result"
+              exit 1
+            fi
+          fi
 
         displayName: Create GitHub release
         workingDirectory: $(Agent.BuildDirectory)/dotnet-source-build/eng
