fixup failure on existing release

diff --git a/eng/templates/stages/release.yml b/eng/templates/stages/release.yml
--- a/eng/templates/stages/release.yml
+++ b/eng/templates/stages/release.yml
@@ -232,8 +232,12 @@ stages:
             2>&1)
 
           if [ $? -ne 0 ]; then
-            echo "##vso[task.logissue type=error]Failed to create the GitHub release: $result"
-            exit 1
+            if [[ "$result" =~ "already exists" ]]; then
+              echo "##vso[task.logissue type=warning]GitHub release $(releaseTag) already exists ($(vmrPublicUrl)/releases/tag/$(releaseTag))"
+            else
+              echo "##vso[task.logissue type=error]Failed to create the GitHub release: $result"
+              exit 1
+            fi
           fi
         displayName: Create GitHub release
         workingDirectory: $(Agent.BuildDirectory)/dotnet-source-build/eng
