[main] Refactor source-build-release pipeline and upload Private.SourceBuilt archive to blob storage (#3095)
* Refactor source-build-release pipeline

* Some updates from code review

* Update release checklist

* Remove accidentally duplicated files

* Fix script path in source-build-release

diff --git a/eng/source-build-release.yml b/eng/source-build-release.yml
--- a/eng/source-build-release.yml
+++ b/eng/source-build-release.yml
@@ -6,198 +6,239 @@ pool:
   demands: ImageOverride -equals 1es-ubuntu-2004
 
 resources:
+  pipelines:
+  - pipeline: dotnet-staging-pipeline-resource
+    source: Stage-DotNet
   repositories:
-    - repository: installer
-      type: github
-      endpoint: dotnet
-      name: dotnet/installer
+  - repository: installer
+    type: github
+    endpoint: dotnet
+    name: dotnet/installer
 
 parameters:
-  - name: sdkVersion
-    displayName: SDK Version
-    type: string
-    default: 6.0.XYY
-
+  - name: createReleaseAnnouncement
+    displayName:  Create Release Announcement
+    type: boolean
+    default: true
+  - name: submitReleasePR
+    displayName: Submit Release PR
+    type: boolean
+    default: true
   - name: useCustomTag
     displayName: Use custom tag?
     type: boolean
     default: false
-
   - name: customTag
     displayName: Installer custom tag
     type: string
     default: v6.0.XYY-source-build
+  - name: useSpecificPipelineRunIDs
+    displayName: Use Specific Pipeline Run IDs
+    type: boolean
+    default: false
+  - name: dotnetInstallerOfficialRunID
+    displayName: dotnet-installer-official-ci run ID
+    type: string
+    default: '200XXXX'
+  - name: dotnetInstallerTarballBuildRunID
+    displayName: dotnet-installer-source-build-tarball-build run ID
+    type: string
+    default: '200XXXX'
+  - name: isDryRun
+    displayName: Testing mode (run the pipeline but don't submit PRs or announcements)
+    type: boolean
+    default: false
 
 variables:
+- template: templates/variables/installer-pipelines.yml
 - group: DotNet-Source-Build-Bot-Secrets
+- group: DotNet-DotNetCli-Storage
 - name: announcementOrg
   value: 'dotnet'
 - name: announcementRepo
   value: 'source-build'
+- name: storageAccountName
+  value: 'dotnetcli'
+- name: blobContainerName
+  value: 'source-built-artifacts'
+- name: blobContainerUploadBaseFilePath
+  ${{ if eq( parameters['isDryRun'], true) }}:
+    value: 'testing'
+  ${{ else }}:
+    value: 'assets'
 
 
-stages:
-
-- stage: Setup
-  jobs:
-  - job: SetupJob
-    displayName: Setup
-    steps:
-    - checkout: installer
-
-    - script: |
-        set -euxo pipefail
-        if [ "${{ parameters.useCustomTag }}" = "True" ] ; then
-          tag=${{ parameters.customTag }}
-          echo "Using custom tag ${tag}"
-        else
-          tag=v${{ parameters.sdkVersion }}
-          echo "Using tag ${tag}"
-        fi
-        set +x
-        echo "##vso[task.setvariable variable=Tag;isOutput=true]${tag}"
-      name: SetTag
-      displayName: Set tag
-
-    - script: |
-        set -euxo pipefail
-        tag="$(SetTag.Tag)"
-        cd $(Build.SourcesDirectory)
-        git show-ref --tags
-        if git rev-parse "$tag" >/dev/null 2>&1; then
-          echo "Tag $tag exists.";
-        else
-          echo "Tag $tag does not exist."
-          exit 1
-        fi
-      displayName: Ensure tag exists
-
-    - script: |
-        set -euxo pipefail
-        cd $(Build.SourcesDirectory)
-        git checkout $(SetTag.Tag)
-        runtime_version=$(cat eng/Version.Details.xml | grep 'Microsoft.NETCore.App.Runtime.win-x64' | grep -P -o -e '(?<=Version=").*?(?=")') # e.g. 6.0.3
-        readarray -d '.' -t version_parts <<< $runtime_version  # split version on dots
-        dotnet_major_minor_version=$(echo "${version_parts[0]}.${version_parts[1]}")
-        set +x
-        echo "##vso[task.setvariable variable=RuntimeVersion;isOutput=true]${runtime_version}"
-        echo "##vso[task.setvariable variable=DotNetMajorMinorVersion;isOutput=true]${dotnet_major_minor_version}"
-      name: SetVersions
-      displayName: Read runtime version from installer
-
-
-- stage: CreateReleaseAnnouncement
+jobs:
+- job: CreateReleaseAnnouncementJob
   displayName: Create Release Announcement
-  dependsOn: Setup
-  jobs:
-  - job: CreateReleaseAnnouncementJob
-    displayName: Create Release Announcement
-    variables:
-    - name: Tag
-      value: $[ stageDependencies.Setup.SetupJob.outputs['SetTag.Tag'] ]
-    - name: DotNetMajorMinorVersion
-      value: $[ stageDependencies.Setup.SetupJob.outputs['SetVersions.DotNetMajorMinorVersion'] ]
-    - name: RuntimeVersion
-      value: $[ stageDependencies.Setup.SetupJob.outputs['SetVersions.RuntimeVersion'] ]
-    steps:
+  condition: eq('${{ parameters.createReleaseAnnouncement }}', true)
+  steps:
+  - checkout: self
+  - checkout: installer
 
-    - script: |
-        set -euxo pipefail
-        query='query { repository(owner: "${{ variables.announcementOrg }}", name: "${{ variables.announcementRepo }}") { id } }'
-        repo_id=$( gh api graphql -f query="$query" --template '{{.data.repository.id}}' )
-        echo ${{ variables.announcementOrg }}/${{ variables.announcementRepo }} repo ID is ${repo_id}
-        echo "##vso[task.setvariable variable=repoId;]${repo_id}"
-      displayName: Get repo ID
-      env:
-        GH_TOKEN: $(BotAccount-dotnet-sb-bot-pat)
+  - template: templates/steps/get-build-info.yml
+    parameters:
+      dotnetStagingPipelineResource: dotnet-staging-pipeline-resource
+      getAssociatedPipelineRuns: false
 
-    - script: |
-        set -euxo pipefail
-        query='query { repository(name: "${{ variables.announcementRepo }}", owner: "${{ variables.announcementOrg }}") { discussionCategories(first: 10) { edges { node { id, name } } } } }'
-        category_id=$( gh api graphql -f query="$query" --template '{{range .data.repository.discussionCategories.edges}}{{if eq .node.name "Announcements"}}{{.node.id}}{{end}}{{end}}' )
-        echo Discussion Category ID is ${category_id}
-        echo "##vso[task.setvariable variable=discussionCategoryId;]${category_id}"
-      displayName: Get announcement discussion category ID
-      env:
-        GH_TOKEN: $(BotAccount-dotnet-sb-bot-pat)
+  - template: templates/steps/validate-tag.yml
+    parameters:
+      useCustomTag: ${{ parameters.useCustomTag }}
+      customTag: ${{ parameters.customTag }}
+      repoPath: $(Build.SourcesDirectory)/installer
 
-    - script: |
-        set -euxo pipefail
-        echo Repo ID is $(repoId)
-        echo Discussion Category ID is $(discussionCategoryId)
+  - script: |
+      set -euxo pipefail
 
-        # Set environment variables that go in the announcement template
-        export TAG=$(Tag)
-        export RUNTIME_VERSION="$(RuntimeVersion)"
-        export DOTNET_MAJOR_MINOR_VERSION="$(DotNetMajorMinorVersion)"
-        export SDK_VERSION="${{ parameters.sdkVersion }}"
-        export TAG_URL="https://github.com/dotnet/installer/releases/tag/$TAG"
-        export RELEASE_NOTES_URL="https://github.com/dotnet/core/blob/main/release-notes/$DOTNET_MAJOR_MINOR_VERSION/$RUNTIME_VERSION/$SDK_VERSION.md"
-        export RELEASE_DATE=$(date +"%B %Y") # e.g. "March 2022"
+      query='query { repository(owner: "${{ variables.announcementOrg }}", name: "${{ variables.announcementRepo }}") { id } }'
+      echo "${query}"
+      repo_id=$( gh api graphql -f query="$query" --template '{{.data.repository.id}}' )
+      echo ${{ variables.announcementOrg }}/${{ variables.announcementRepo }} repo ID is ${repo_id}
 
-        template="$(envsubst < $(Build.SourcesDirectory)/eng/source-build-release-announcement.md)"
-        # Get the line in the template that is prefixed with "Title:" and remove the prefix
-        title=$(echo "$template" | grep "^Title:" | cut -d " " -f2-)
-        # Get the inverse of the above selection
-        body=$(echo "$template" | grep -v "^Title:")
+      query='query { repository(name: "${{ variables.announcementRepo }}", owner: "${{ variables.announcementOrg }}") { discussionCategories(first: 10) { edges { node { id, name } } } } }'
+      echo "${query}"
+      category_id=$( gh api graphql -f query="$query" --template '{{range .data.repository.discussionCategories.edges}}{{if eq .node.name "Announcements"}}{{.node.id}}{{end}}{{end}}' )
+      echo Discussion Category ID is ${category_id}
 
-        query='mutation($repoId: ID!, $categoryId: ID!, $body: String!, $title: String!) { createDiscussion(input: {repositoryId: $repoId, categoryId: $categoryId, body: $body, title: $title}) { discussion { url } } }'
-        announcement_url=$( gh api graphql -F repoId=$(repoId) -F categoryId=$(discussionCategoryId) -F body="${body}" -F title="${title}" -f query="$query" --template '{{.data.createDiscussion.discussion.url}}' )
+      echo "##vso[task.setvariable variable=RepoId;]${repo_id}"
+      echo "##vso[task.setvariable variable=DiscussionCategoryId;]${category_id}"
+    displayName: Get category IDs
+    env:
+      GH_TOKEN: $(BotAccount-dotnet-sb-bot-pat)
+
+  - script: |
+      set -euxo pipefail
+      echo Repo ID is $(RepoId)
+      echo Discussion Category ID is $(DiscussionCategoryId)
+
+      # Set environment variables that go in the announcement template
+      export TAG=$(Tag)
+      export RUNTIME_VERSION="$(RuntimeVersion)"
+      export RELEASE_CHANNEL="$(ReleaseChannel)"
+      export SDK_VERSION="$(SdkVersion)"
+      export TAG_URL="https://github.com/dotnet/installer/releases/tag/$TAG"
+      export RELEASE_NOTES_URL="https://github.com/dotnet/core/blob/main/release-notes/$RELEASE_CHANNEL/$RUNTIME_VERSION/$SDK_VERSION.md"
+      export RELEASE_DATE=$(date +"%B %Y") # e.g. "March 2022"
+
+      template_path="$(Build.SourcesDirectory)/$(Build.Repository.Name)/eng"
+      template="$(envsubst < ${template_path}/source-build-release-announcement.md)"
+      # Get the line in the template that is prefixed with "Title:" and remove the prefix
+      title=$(echo "$template" | grep "^Title:" | cut -d " " -f2-)
+      # Get the inverse of the above selection
+      body=$(echo "$template" | grep -v "^Title:")
+
+      query='mutation($RepoId: ID!, $categoryId: ID!, $body: String!, $title: String!) { createDiscussion(input: {repositoryId: $RepoId, categoryId: $categoryId, body: $body, title: $title}) { discussion { url } } }'
+
+      if [ ${{ parameters.isDryRun }} = True ]; then
+        echo "Doing a dry run, not submitting announcement."
+        echo "Announcement title: ${title}"
+        echo "Announcement body: ${body}"
+      else
+        echo "Submitting announcement."
+        announcement_url=$( gh api graphql -F RepoId=$(RepoId) -F categoryId=$(DiscussionCategoryId) -F body="${body}" -F title="${title}" -f query="$query" --template '{{.data.createDiscussion.discussion.url}}' )
 
         echo "Announcement URL: $announcement_url"
         echo "Tag URL: $TAG_URL"
         echo "Release Notes URL: $RELEASE_NOTES_URL"
-      displayName: Submit announcement discussion
-      env:
-        GH_TOKEN: $(BotAccount-dotnet-sb-bot-pat)
+      fi
+    displayName: Submit announcement discussion
+    env:
+      GH_TOKEN: $(BotAccount-dotnet-sb-bot-pat)
 
-
-- stage: SubmitReleasePr
+- job: SubmitReleasePrJob
   displayName: Submit Release PR
-  dependsOn: Setup
-  jobs:
-  - job: SubmitReleasePrJob
-    displayName: Submit Release PR
-    variables:
-    - name: DotNetMajorMinorVersion
-      value: $[ stageDependencies.Setup.SetupJob.outputs['SetVersions.DotNetMajorMinorVersion'] ]
-    - name: RuntimeVersion
-      value: $[ stageDependencies.Setup.SetupJob.outputs['SetVersions.RuntimeVersion'] ]
-    - name: TargetRepo
-      value: dotnet/installer
-    - name: ForkRepo
-      value: dotnet-sb-bot/installer
+  condition: eq('${{ parameters.submitReleasePR }}', true)
+  variables:
+  - name: TargetRepo
+    value: dotnet/installer
+  - name: ForkRepo
+    value: dotnet-sb-bot/installer
 
-    steps:
+  steps:
+  - checkout: self
+  - checkout: installer
 
-    - script: |
-        sudo apt-get update
-        sudo apt-get install -y jq
-      displayName: Install tools
+  - template: templates/steps/get-build-info.yml
+    parameters:
+      dotnetStagingPipelineResource: dotnet-staging-pipeline-resource
+      getAssociatedPipelineRuns: true
+      useSpecificPipelineRunIDs: ${{ parameters.useSpecificPipelineRunIDs }}
+      dotnetInstallerOfficialRunID: ${{ parameters.dotnetInstallerOfficialRunID }}
+      dotnetInstallerTarballBuildRunID: ${{ parameters.dotnetInstallerTarballBuildRunID }}
 
-    - script: |
-        set -euxo pipefail
+  - template: templates/steps/validate-tag.yml
+    parameters:
+      useCustomTag: ${{ parameters.useCustomTag }}
+      customTag: ${{ parameters.customTag }}
+      repoPath: $(Build.SourcesDirectory)/installer
 
-        export RELEASE_DATE=$(date +"%B %Y") # e.g. "March 2022"
-        export RUNTIME_VERSION="$(RuntimeVersion)"
-        export SDK_VERSION="${{ parameters.sdkVersion }}"
+  - script: |
+      set -euo pipefail
+      if [ '$(ReleaseChannel)' == '6.0' ]; then
+        echo "##vso[task.setvariable variable=TarballBuildArtifactLeg]Build_Tarball_x64 CentOS7-Offline_Artifacts"
+      elif [ '$(ReleaseChannel)' == '7.0' ]; then
+        echo "##vso[task.setvariable variable=TarballBuildArtifactLeg]Build_Tarball_x64 CentOSStream8-Offline_Artifacts"
+      else
+        echo "##vso[task.logissue type=error]Release channel $(ReleaseChannel) is not supported. Exiting..."
+        exit 1
+      fi
+    displayName: Set artifact name
 
-        template="$(envsubst < $(Build.SourcesDirectory)/eng/source-build-release-pr.md)"
-        # Get the line in the template that is prefixed with "Title:" and remove the prefix
-        title=$(echo "$template" | grep "^Title:" | cut -d " " -f2-)
-        # Get the inverse of the above selection
-        body=$(echo "$template" | grep -v "^Title:")
+  - task: DownloadPipelineArtifact@2
+    name: DownloadSourceBuiltArtifactsStep
+    displayName: Download Source-Built Artifacts
+    inputs:
+      source: 'specific'
+      project: '$(azDoProject)'
+      pipeline: '$(installerTarabllBuildCiPipelineId)'
+      runVersion: 'specific'
+      runId: '$(InstallerTarballBuildRunId)'
+      artifact: '$(TarballBuildArtifactLeg)'
+      patterns: 'Private.SourceBuilt.Artifacts.$(SdkVersion).tar.gz'
 
-        cd $(Agent.WorkFolder)/
+  - template: templates/steps/upload-to-blob-storage.yml
+    parameters:
+      file: '$(PIPELINE.WORKSPACE)/Private.SourceBuilt.Artifacts.$(SdkVersion).tar.gz'
+      accountName: '$(storageAccountName)'
+      containerName: '$(blobContainerName)'
+      uploadPath: '$(blobContainerUploadBaseFilePath)'
+      azureStorageKey: '$(dotnetcli-storage-key)'
 
-        $(Build.SourcesDirectory)/eng/submit-source-build-release-pr.sh \
+  - script: |
+      set -euxo pipefail
+
+      export RELEASE_DATE=$(date +"%B %Y") # e.g. "March 2022"
+      export RUNTIME_VERSION="$(RuntimeVersion)"
+      export SDK_VERSION="$(SdkVersion)"
+      
+      source_build_repo_root="$(Build.SourcesDirectory)/$(Build.Repository.Name)"
+      template_path="${source_build_repo_root}/eng"
+      template="$(envsubst < ${template_path}/source-build-release-pr.md)"
+      # Get the line in the template that is prefixed with "Title:" and remove the prefix
+      title=$(echo "$template" | grep "^Title:" | cut -d " " -f2-)
+      # Get the inverse of the above selection
+      body=$(echo "$template" | grep -v "^Title:")
+
+      cd $(Agent.WorkFolder)/
+
+      echo "TargetRepo: $(TargetRepo)"
+      echo "ForkRepo: $(ForkRepo)"
+      echo "SdkVersion: $(SdkVersion)"
+      echo "title: ${title}"
+      echo "body: ${body}"
+
+      if [ ${{ parameters.isDryRun }} = True ]; then
+        echo "Doing a dry run, not submitting PR."
+      else
+        echo "Submitting PR"
+        ${source_build_repo_root}/eng/submit-source-build-release-pr.sh \
             --setupGitAuth \
             --targetRepo $(TargetRepo) \
             --forkRepo $(ForkRepo) \
-            --sdkVersion ${{ parameters.sdkVersion }} \
+            --sdkVersion $(SdkVersion) \
             --title "${title}" \
             --body "${body}"
-
-      displayName: Submit PR
-      env:
-        GH_TOKEN: $(BotAccount-dotnet-sb-bot-pat)
+      fi
+    displayName: Submit Release PR
+    env:
+      GH_TOKEN: $(BotAccount-dotnet-sb-bot-pat)
