Checkpoint

diff --git a/patches/cli/0003-Don-t-pull-down-stage-0-from-the-internet.patch b/patches/cli/0003-Don-t-pull-down-stage-0-from-the-internet.patch
--- a/patches/cli/0003-Don-t-pull-down-stage-0-from-the-internet.patch
+++ b/patches/cli/0003-Don-t-pull-down-stage-0-from-the-internet.patch
@@ -1,7 +1,7 @@
-From a0198716a03a9fdca82125487a4223cc55a06f5c Mon Sep 17 00:00:00 2001
+From 320a9038e53d41d3ded0f832a44c55bf8c7abbb4 Mon Sep 17 00:00:00 2001
 From: Matt Ellis <matell@microsoft.com>
 Date: Mon, 22 May 2017 11:37:59 -0700
-Subject: [PATCH 3/3] Don't pull down stage 0 from the internet
+Subject: [PATCH 3/5] Don't pull down stage 0 from the internet
 
 The composed build will set `PREBUILT_DOTNET_TOOL_DIR` to a location
 where the dotnet tool can be copied from.
@@ -10,11 +10,36 @@ Long term we should get rid of the copy in favor of just using one
 from a common location, but some of the Stage0 logic in the CLI build
 system will need to change, I think.
 ---
- run-build.sh | 15 +--------------
- 1 file changed, 1 insertion(+), 14 deletions(-)
+ build_projects/update-dependencies/update-dependencies.sh | 11 ++++-------
+ run-build.sh                                              | 15 +--------------
+ 2 files changed, 5 insertions(+), 21 deletions(-)
 
+diff --git a/build_projects/update-dependencies/update-dependencies.sh b/build_projects/update-dependencies/update-dependencies.sh
+index 4781c84..8a0d7f9 100755
+--- a/build_projects/update-dependencies/update-dependencies.sh
++++ b/build_projects/update-dependencies/update-dependencies.sh
+@@ -30,15 +30,12 @@ if [ -z "${DOTNET_INSTALL_DIR:-}" ]; then
+    export DOTNET_INSTALL_DIR=$REPO_ROOT/.dotnet_stage0/x64
+ fi
+ 
+-# Install a stage 0
+-echo "Installing .NET Core CLI Stage 0"
+-$REPO_ROOT/scripts/obtain/dotnet-install.sh -Channel master -Architecture x64
+-
+-if [ $? -ne 0 ]; then
+-    echo "Failed to install stage 0"
+-    exit 1
++if [ ! -d "$DOTNET_INSTALL_DIR" ]; then
++    mkdir -p $DOTNET_INSTALL_DIR
+ fi
+ 
++cp -r $DOTNET_TOOL_DIR/* $DOTNET_INSTALL_DIR/
++
+ # Put the stage 0 on the path
+ export PATH=$DOTNET_INSTALL_DIR:$PATH
+ 
 diff --git a/run-build.sh b/run-build.sh
-index 726e6d3bd..3faab1ffd 100755
+index 726e6d3..3faab1f 100755
 --- a/run-build.sh
 +++ b/run-build.sh
 @@ -155,20 +155,7 @@ export VSTEST_TRACE_BUILD=1
@@ -40,5 +65,5 @@ index 726e6d3bd..3faab1ffd 100755
  # Put stage 0 on the PATH (for this shell only)
  PATH="$DOTNET_INSTALL_DIR:$PATH"
 -- 
-2.11.0
+1.8.3.1
 
